defaults:
  - visualization: eval

num_workers: 2
batch_size: 1
cuda: 0
weight_name: latest
enable_cudnn: True
checkpoint_dir: '/home/cisong/ForAINet/outputs/pretrained' 
model_name: PointGroup-PAPER
precompute_multi_scale: True
enable_dropout: False
voting_runs: 1
data:
  fold:
  - /home/cisong/ForAINet/data/TranCanadaHwy/TranCanadaHwy.ply

tracker_options:
  full_res: True
  make_submission: True
  ply_output: "vote1regular.ply"

hydra:
  run:
    dir: outputs/TranCanadaHwy/prediction/${now:%Y-%m-%d_%H}
    
